site_name: Arranges
repo_url: https://github.com/bitplane/arranges/
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'blue'
  features:
    - navigation.expand_single_toc_entry
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - 'index.md'
 - 'construction.md'
 - 'iteration.md'
 - 'operators.md'
 - 'models.md'
 - 'pydoc.md'
 - 'LICENSE'
